import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import { execSync } from 'child_process'
import { log } from '../debug'
import type { AgentSpawnOpts } from './index'

function shellQuote(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'"
}

const HARNESS_PLUGIN_SIGNATURE = 'harness-opencode-plugin'

export const PLUGIN_PATH = join(homedir(), '.config', 'opencode', 'plugins', 'tatsu-status.js')

export const defaultCommand = 'opencode'
export const assignsSessionId = false

export const hookEvents = [
  'session.created',
  'tool.execute.before',
  'tool.execute.after',
  'session.idle',
  'permission.asked',
  'permission.replied'
]

function pluginDir(): string {
  return join(homedir(), '.config', 'opencode', 'plugins')
}

function makePluginContent(): string {
  return `// ${HARNESS_PLUGIN_SIGNATURE}
// Auto-generated by Tatsu. Emits status events to /tmp/tatsu-status.
const fs = require('fs');
const path = require('path');

function emit(event, payload) {
  const terminalId = process.env.TATSU_TERMINAL_ID || process.env.HARNESS_TERMINAL_ID || process.env.CLAUDE_HARNESS_ID;
  if (!terminalId) return;
  const dir = '/tmp/tatsu-status';
  fs.mkdirSync(dir, { recursive: true });
  const line = JSON.stringify({ event, ts: Math.floor(Date.now() / 1000), payload }) + '\\n';
  fs.appendFileSync(path.join(dir, terminalId + '.ndjson'), line);
}

module.exports = {
  async onEvent(ctx) {
    const ev = ctx.event;
    if (!ev) return;
    switch (ev.type) {
      case 'session.created':
        emit('UserPromptSubmit', { session_id: ev.payload?.session?.id });
        break;
      case 'tool.execute.before':
        emit('PreToolUse', {
          session_id: ev.payload?.session?.id,
          tool_name: ev.payload?.tool?.name,
          tool_input: ev.payload?.tool?.input
        });
        break;
      case 'tool.execute.after':
        emit('PostToolUse', {
          session_id: ev.payload?.session?.id,
          tool_name: ev.payload?.tool?.name,
          tool_input: ev.payload?.tool?.input
        });
        break;
      case 'session.idle':
        emit('Stop', { session_id: ev.payload?.session?.id });
        break;
      case 'permission.asked':
        emit('Notification', {
          notification_type: 'permission_prompt',
          session_id: ev.payload?.session?.id,
          tool_name: ev.payload?.permission?.tool?.name,
          tool_input: ev.payload?.permission?.tool?.input
        });
        break;
      case 'permission.replied':
        emit('UserPromptSubmit', { session_id: ev.payload?.session?.id });
        break;
    }
  }
};
`
}

export function hooksInstalled(): boolean {
  try {
    if (!existsSync(PLUGIN_PATH)) return false
    const content = readFileSync(PLUGIN_PATH, 'utf-8')
    return content.includes(HARNESS_PLUGIN_SIGNATURE)
  } catch {
    return false
  }
}

export function installHooks(): void {
  const dir = pluginDir()
  log('hooks', `installing Opencode plugin into ${PLUGIN_PATH}`)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(PLUGIN_PATH, makePluginContent())
}

export function uninstallHooks(): void {
  if (!existsSync(PLUGIN_PATH)) return
  try {
    const content = readFileSync(PLUGIN_PATH, 'utf-8')
    if (content.includes(HARNESS_PLUGIN_SIGNATURE)) {
      unlinkSync(PLUGIN_PATH)
      log('hooks', `uninstalled Opencode plugin from ${PLUGIN_PATH}`)
    }
  } catch {
    // ignore
  }
}

export function stripHooksFromWorktree(_worktreePath: string): boolean {
  // Opencode has no legacy per-worktree plugin path.
  return false
}

export function sessionFileExists(_cwd: string, sessionId: string): boolean {
  try {
    execSync(`opencode export ${sessionId}`, { stdio: 'pipe', timeout: 5000 })
    return true
  } catch {
    return false
  }
}

export function latestSessionId(_cwd: string): string | null {
  try {
    const output = execSync('opencode session list --format json --max-count 1', {
      stdio: 'pipe',
      timeout: 5000,
      encoding: 'utf-8'
    })
    const parsed = JSON.parse(output) as Array<{ id?: string }>
    if (Array.isArray(parsed) && parsed.length > 0 && typeof parsed[0].id === 'string') {
      return parsed[0].id
    }
    return null
  } catch {
    return null
  }
}

export function buildSpawnArgs(opts: AgentSpawnOpts): string {
  let cmd = opts.command

  if (opts.model && !opts.command.includes('--model') && !opts.command.includes('-m ')) {
    cmd += ` --model ${shellQuote(opts.model)}`
  }

  if (opts.sessionId) {
    const exists = sessionFileExists(opts.cwd, opts.sessionId)
    if (exists) {
      cmd += ` --session ${shellQuote(opts.sessionId)}`
      if (opts.initialPrompt) {
        cmd += ` --prompt ${shellQuote(opts.initialPrompt)}`
      }
      return cmd
    }
  }

  if (opts.initialPrompt) {
    cmd += ` --prompt ${shellQuote(opts.initialPrompt)}`
  }

  return cmd
}
