import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync, readdirSync, statSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import { log } from '../debug'
import { shellQuote } from '../shell-quote'
import type { AgentSpawnOpts } from './index'


const HARNESS_EXTENSION_SIGNATURE = 'harness-pi-extension'
const LATEST_SESSION_CACHE_TTL_MS = 2_000

type LatestSessionCacheEntry = { value: string | null; expiresAt: number }

const latestSessionCache = new Map<string, LatestSessionCacheEntry>()

export const EXTENSION_PATH = join(homedir(), '.pi', 'agent', 'extensions', 'harness-status.ts')

export const defaultCommand = 'pi'
export const assignsSessionId = false

export const hookEvents = [
  'session_start',
  'agent_start',
  'agent_end',
  'tool_execution_start',
  'tool_execution_end',
  'session_shutdown'
]

function extensionDir(): string {
  return join(homedir(), '.pi', 'agent', 'extensions')
}

function makeExtensionContent(): string {
  return `// ${HARNESS_EXTENSION_SIGNATURE}
// Auto-generated by Harness. Emits status events to /tmp/harness-status.
// Pi auto-loads .ts files from ~/.pi/agent/extensions/ via jiti (no compilation needed).

// @ts-ignore
const path = require('path');
// @ts-ignore
const { mkdir, appendFile } = require('fs').promises;
const dir = '/tmp/harness-status';
const ensureDirReady = mkdir(dir, { recursive: true }).catch(() => undefined);

function toolName(payload: any) {
  return payload?.tool_name ?? payload?.tool?.name;
}

function toolInput(payload: any) {
  return payload?.tool_input ?? payload?.tool?.input ?? payload?.input;
}

async function emit(event: string, payload: Record<string, unknown>) {
  const terminalId = process.env.HARNESS_TERMINAL_ID || process.env.CLAUDE_HARNESS_ID;
  if (!terminalId) return;
  await ensureDirReady;
  try {
    const line = JSON.stringify({ event, ts: Math.floor(Date.now() / 1000), payload }) + '\\n';
    await appendFile(path.join(dir, terminalId + '.ndjson'), line);
  } catch { /* ignore */ }
}

module.exports = {
  async onEvent(ctx: any) {
    const ev = ctx.event;
    if (!ev) return;
    let sessionId: string | undefined;
    try {
      sessionId = ctx.sessionManager?.getSessionFile?.();
    } catch { /* ignore */ }
    switch (ev.type) {
      case 'session_start':
        await emit('UserPromptSubmit', { session_id: sessionId });
        break;
      case 'agent_start':
        await emit('UserPromptSubmit', { session_id: sessionId });
        break;
      case 'tool_execution_start':
        await emit('PreToolUse', {
          session_id: sessionId,
          tool_name: toolName(ev.payload),
          tool_input: toolInput(ev.payload)
        });
        break;
      case 'tool_execution_end':
        await emit('PostToolUse', {
          session_id: sessionId,
          tool_name: toolName(ev.payload),
          tool_input: toolInput(ev.payload)
        });
        break;
      case 'agent_end':
        await emit('Stop', { session_id: sessionId, transcript_path: sessionId });
        break;
      case 'session_shutdown':
        await emit('Stop', { session_id: sessionId, transcript_path: sessionId });
        break;
    }
  }
};`
}

export function hooksInstalled(): boolean {
  try {
    if (!existsSync(EXTENSION_PATH)) return false
    const content = readFileSync(EXTENSION_PATH, 'utf-8')
    return content.includes(HARNESS_EXTENSION_SIGNATURE)
  } catch {
    return false
  }
}

export function installHooks(): void {
  const dir = extensionDir()
  log('hooks', `installing Pi extension into ${EXTENSION_PATH}`)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(EXTENSION_PATH, makeExtensionContent())
}

export function uninstallHooks(): void {
  if (!existsSync(EXTENSION_PATH)) return
  try {
    const content = readFileSync(EXTENSION_PATH, 'utf-8')
    if (content.includes(HARNESS_EXTENSION_SIGNATURE)) {
      unlinkSync(EXTENSION_PATH)
      log('hooks', `uninstalled Pi extension from ${EXTENSION_PATH}`)
    }
  } catch {
    // ignore
  }
}

export function stripHooksFromWorktree(_worktreePath: string): boolean {
  return false
}

export function sessionFileExists(_cwd: string, sessionId: string): boolean {
  try {
    // Pi hook events always provide absolute session file paths.
    if (sessionId.startsWith('/') || sessionId.startsWith('~')) {
      const resolved = sessionId.startsWith('~') ? join(homedir(), sessionId.slice(1)) : sessionId
      return existsSync(resolved)
    }
    return false
  } catch {
    return false
  }
}

export function latestSessionId(cwd: string): string | null {
  const now = Date.now()
  const cached = latestSessionCache.get(cwd)
  if (cached && cached.expiresAt > now) return cached.value

  let bestId: string | null = null
  try {
    const sessionsDir = join(homedir(), '.pi', 'agent', 'sessions')
    if (!existsSync(sessionsDir)) {
      latestSessionCache.set(cwd, { value: null, expiresAt: now + LATEST_SESSION_CACHE_TTL_MS })
      return null
    }
    // Pi stores sessions in subdirs named after the cwd: --path--/timestamp_uuid.jsonl
    const cwdSlug = '--' + cwd.replace(/^\//, '').split('/').join('--') + '--'
    const dirs = readdirSync(sessionsDir)
    let bestMtime = -Infinity
    for (const entry of dirs) {
      if (entry !== cwdSlug) continue
      const fullPath = join(sessionsDir, entry)
      try {
        const st = statSync(fullPath)
        if (st.isDirectory()) {
          const subEntries = readdirSync(fullPath)
          for (const sub of subEntries) {
            if (sub.endsWith('.jsonl')) {
              const fp = join(fullPath, sub)
              const mtime = statSync(fp).mtimeMs
              if (mtime > bestMtime) {
                bestMtime = mtime
                bestId = fp
              }
            }
          }
        } else if (entry.endsWith('.jsonl')) {
          if (st.mtimeMs > bestMtime) {
            bestMtime = st.mtimeMs
            bestId = fullPath
          }
        }
      } catch { /* skip */ }
    }
    latestSessionCache.set(cwd, { value: bestId, expiresAt: now + LATEST_SESSION_CACHE_TTL_MS })
    return bestId
  } catch {
    latestSessionCache.set(cwd, { value: null, expiresAt: now + LATEST_SESSION_CACHE_TTL_MS })
    return null
  }
}

export function buildSpawnArgs(opts: AgentSpawnOpts): string {
  let cmd = opts.command

  if (opts.model && !opts.command.includes('--model')) {
    cmd += ` --model ${shellQuote(opts.model)}`
  }

  if (opts.sessionName && !opts.command.includes('--name')) {
    cmd += ` --name ${shellQuote(opts.sessionName)}`
  }

  if (opts.sessionId && !opts.command.includes('--session')) {
    const exists = sessionFileExists(opts.cwd, opts.sessionId)
    if (exists) {
      cmd += ` --session ${shellQuote(opts.sessionId)}`
      if (opts.initialPrompt) {
        cmd += ` ${shellQuote(opts.initialPrompt)}`
      }
      return cmd
    }
  }

  if (opts.initialPrompt) {
    cmd += ` ${shellQuote(opts.initialPrompt)}`
  }

  return cmd
}