import { readFileSync, writeFileSync, mkdirSync, existsSync, unlinkSync, readdirSync, statSync } from 'fs'
import { join } from 'path'
import { homedir } from 'os'
import { log } from '../debug'
import type { AgentSpawnOpts } from './index'

function shellQuote(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'"
}

const HARNESS_EXTENSION_SIGNATURE = 'harness-pi-extension'

export const EXTENSION_PATH = join(homedir(), '.pi', 'agent', 'extensions', 'harness-status.ts')

export const defaultCommand = 'pi'
export const assignsSessionId = false

export const hookEvents = [
  'session_start',
  'agent_start',
  'agent_end',
  'tool_execution_start',
  'tool_execution_end',
  'session_shutdown'
]

function extensionDir(): string {
  return join(homedir(), '.pi', 'agent', 'extensions')
}

function makeExtensionContent(): string {
  return `// ${HARNESS_EXTENSION_SIGNATURE}
// Auto-generated by Harness. Emits status events to /tmp/harness-status.
// Pi auto-loads .ts files from ~/.pi/agent/extensions/ via jiti (no compilation needed).

function emit(event: string, payload: Record<string, unknown>) {
  const terminalId = process.env.HARNESS_TERMINAL_ID || process.env.CLAUDE_HARNESS_ID;
  if (!terminalId) return;
  const dir = '/tmp/harness-status';
  // @ts-ignore - fs is available in jiti runtime
  const fs = require('fs');
  // @ts-ignore
  const path = require('path');
  fs.mkdirSync(dir, { recursive: true });
  const line = JSON.stringify({ event, ts: Math.floor(Date.now() / 1000), payload }) + '\\n';
  fs.appendFileSync(path.join(dir, terminalId + '.ndjson'), line);
}

module.exports = {
  async onEvent(ctx: any) {
    const ev = ctx.event;
    if (!ev) return;
    const sessionId = ctx.sessionManager?.getSessionFile?.();
    switch (ev.type) {
      case 'session_start':
        emit('UserPromptSubmit', { session_id: sessionId });
        break;
      case 'agent_start':
        emit('UserPromptSubmit', { session_id: sessionId });
        break;
      case 'tool_execution_start':
        emit('PreToolUse', {
          session_id: sessionId,
          tool_name: ev.payload?.tool_name,
          tool_input: ev.payload?.tool_input
        });
        break;
      case 'tool_execution_end':
        emit('PostToolUse', {
          session_id: sessionId,
          tool_name: ev.payload?.tool_name,
          tool_input: ev.payload?.tool_input
        });
        break;
      case 'agent_end':
        emit('Stop', { session_id: sessionId, transcript_path: sessionId });
        break;
      case 'session_shutdown':
        emit('Stop', { session_id: sessionId, transcript_path: sessionId });
        break;
    }
  }
};
`
}

export function hooksInstalled(): boolean {
  try {
    if (!existsSync(EXTENSION_PATH)) return false
    const content = readFileSync(EXTENSION_PATH, 'utf-8')
    return content.includes(HARNESS_EXTENSION_SIGNATURE)
  } catch {
    return false
  }
}

export function installHooks(): void {
  const dir = extensionDir()
  log('hooks', `installing Pi extension into ${EXTENSION_PATH}`)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
  writeFileSync(EXTENSION_PATH, makeExtensionContent())
}

export function uninstallHooks(): void {
  if (!existsSync(EXTENSION_PATH)) return
  try {
    const content = readFileSync(EXTENSION_PATH, 'utf-8')
    if (content.includes(HARNESS_EXTENSION_SIGNATURE)) {
      unlinkSync(EXTENSION_PATH)
      log('hooks', `uninstalled Pi extension from ${EXTENSION_PATH}`)
    }
  } catch {
    // ignore
  }
}

export function stripHooksFromWorktree(_worktreePath: string): boolean {
  return false
}

export function sessionFileExists(_cwd: string, sessionId: string): boolean {
  try {
    // Pi sessions are absolute paths to .jsonl files
    if (sessionId.startsWith('/') || sessionId.startsWith('~')) {
      const resolved = sessionId.startsWith('~') ? join(homedir(), sessionId.slice(1)) : sessionId
      return existsSync(resolved)
    }
    // Otherwise search ~/.pi/agent/sessions/ for matching file
    const sessionsDir = join(homedir(), '.pi', 'agent', 'sessions')
    if (!existsSync(sessionsDir)) return false
    const entries = readdirSync(sessionsDir)
    for (const entry of entries) {
      if (entry.includes(sessionId) || entry.endsWith(sessionId)) {
        const fullPath = join(sessionsDir, entry)
        if (statSync(fullPath).isFile()) return true
      }
    }
    return false
  } catch {
    return false
  }
}

export function latestSessionId(_cwd: string): string | null {
  try {
    const sessionsDir = join(homedir(), '.pi', 'agent', 'sessions')
    if (!existsSync(sessionsDir)) return null
    const dirs = readdirSync(sessionsDir)
    const files: Array<{ path: string; mtime: number }> = []
    for (const entry of dirs) {
      const fullPath = join(sessionsDir, entry)
      try {
        const st = statSync(fullPath)
        if (st.isDirectory()) {
          // Pi stores sessions in subdirs: --path--/timestamp_uuid.jsonl
          const subEntries = readdirSync(fullPath)
          for (const sub of subEntries) {
            if (sub.endsWith('.jsonl')) {
              const fp = join(fullPath, sub)
              files.push({ path: fp, mtime: statSync(fp).mtimeMs })
            }
          }
        } else if (entry.endsWith('.jsonl')) {
          files.push({ path: fullPath, mtime: st.mtimeMs })
        }
      } catch { /* skip */ }
    }
    if (files.length === 0) return null
    files.sort((a, b) => b.mtime - a.mtime)
    return files[0].path
  } catch {
    return null
  }
}

export function buildSpawnArgs(opts: AgentSpawnOpts): string {
  let cmd = opts.command

  if (opts.model && !opts.command.includes('--model')) {
    cmd += ` --model ${shellQuote(opts.model)}`
  }

  if (opts.sessionName && !opts.command.includes('--name')) {
    cmd += ` --name ${shellQuote(opts.sessionName)}`
  }

  if (opts.sessionId) {
    const exists = sessionFileExists(opts.cwd, opts.sessionId)
    if (exists) {
      cmd += ` --session ${shellQuote(opts.sessionId)}`
      if (opts.initialPrompt) {
        cmd += ` ${shellQuote(opts.initialPrompt)}`
      }
      return cmd
    }
  }

  if (opts.initialPrompt) {
    cmd += ` ${shellQuote(opts.initialPrompt)}`
  }

  return cmd
}